dp = {
            "E1-01" => "Abnormal Platen Glass scanning. Home Position Sensor connector is disconnected. Home Position Sensor is defective. Scanner Motor connector is disconnected. Scanner Motor is defective. Scanning Mechanism is defective. DRV PCB connector is disconnected. 7. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E1-20" => "Laser Unit horizontal synchronization LSU connector is disconnected. LSU is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E1-21" => "Laser Unit horizontal synchronization. LSU connector is disconnected. LSU is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E1-22" => "Polygon Motor synchronization. Polygon Motor connector is disconnected. SPC PCB connector is disconnected. Polygon Motor is defective. LVPS is defective. DRV PCB is defective",
            "E1-31" => "Scanning Lamp (not turned On) Scanning Lamp connector is disconnected. Scanning Lamp is defective. ACD PCB connector is disconnected. ACD PCB is defective",
            "E13" => "Toner Sensor Toner Bottle is not installed correctly. Out of Toner. Toner Sensor is disconnected. Toner Sensor is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E2-01" => "Lift Motor rotation (1st Paper Tray) Level Sensor connector is disconnected. Level Sensor is defective. Lift Mechanism is defective. Lift Motor connector is disconnected. Lift Motor is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E2-02" => "Lift Motor rotation (2nd Paper Tray) Level Sensor connector is disconnected. Level Sensor is defective. Lift Mechanism is defective. Lift Motor connector is disconnected. Lift Motor is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E2-03" => "Lift Motor rotation (3rd Paper Tray) Level Sensor connector is disconnected. Level Sensor is defective. Lift Mechanism is defective. Lift Motor connector is disconnected. Lift Motor is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E2-04" => "Lift Motor rotation (4th Paper Tray) Level Sensor connector is disconnected. Level Sensor is defective. Lift Mechanism is defective. Lift Motor connector is disconnected. Lift Motor is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E2-06" => "LCT lift operation(UP) LCT connector is disconnected. Upper Limit Sensor connector is disconnected. Upper Limit Sensor is defective. Lift Mechanism is defective. Lift Motor connector is disconnected. Lift Motor is defective. Lower Limit Sensor connector is disconnected. Lower Limit Sensor is defective. LCT PCB connector is disconnected. LCT PCB is defective. LVPS connector is disconnected. LVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E2-07" => "LCT lift operation (DOWN) LCT connector is disconnected. Upper Limit Sensor connector is disconnected. Upper Limit Sensor is defective. Lift Mechanism is defective. Lift Motor connector is disconnected. Lift Motor is defective. Lower Limit Sensor connector is disconnected. Lower Limit Sensor is defective. LCT PCB connector is disconnected. LCT PCB is defective. LVPS connector is disconnected. LVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E2-10" => "System Console Drive Motor rotation System Console Cable is disconnected. Drive Mechanism is defective. Drive Motor connector is disconnected. Drive Motor is defective. APF PCB connector is disconnected. APF PCB is defective. LVPS connector is disconnected. 8. LVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-01" => "Toner Bottle Motor rotation Toner Bottle Home Position Sensor connector is disconnected. Toner Bottle Home Position Sensor is defective. Toner Bottle Motor connector is disconnected. Toner Bottle Motor is defective. Toner Bottle Motor Drive Mechanism is defective. Toner Bottle is installed incorrectly. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-03" => "Toner Density Sensor gain Sensor connector is disconnected. Sensor is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-10" => "High Voltage Power Supply leak (1) HVPS connector is disconnected. HVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-11" => "High Voltage Power Supply leak (2) HVPS connector is disconnected. HVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-12" => "High Voltage Power Supply leak (3) HVPS connector is disconnected. HVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-13" => "High Voltage Power Supply leak (4) HVPS connector is disconnected. HVPS is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-20" => "Main Motor rotation Drive Mechanism is defective. Main Motor connector is disconnected. Main Motor is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E3-21" => "Dust Collection Fan Motor rotation Dust Collection Fan connector is disconnected. Dust Collection Fan is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E3-23" => "Suction Fan rotation Suction Fan connector is disconnected. Suction Fan is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E3-24" => "Ozone Fan 2 rotation Ozone Fan 2 connector is disconnected. Ozone Fan 2 is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E3-25" => "Drum Motor rotation Drum Drive Mechanism is defective. Drum Unit is defective. Drum Motor connector is disconnected. Drum Motor is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E3-40" => "Copy Density Sensor output adjustment Sensor connector is disconnected. Sensor is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E3-51" => "Corona Wire cleaning Cleaner Home Position Sensor 1 connector is disconnected. Cleaner Home Position Sensor 1 is defective. Cleaner Home Position Sensor 2 connector is disconnected. Cleaner Home Position Sensor 2 is defective. Cleaner Motor Drive Mechanism is defective. Corona Mechanism is defective. Cleaner Motor connector is disconnected. Cleaner Motor is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E3-60" => "Toner Waste collection Toner Waste is clogged up in the pipe. Toner Waste Mechanism is defective. (Refer to Flow Chart Below)Lock Detect Sensor connector is disconnected. Lock Detect Sensor is defective. DRV PCB connector is disconnected. DRV PCB is defective.SPC PCB connector is disconnected. SPC PCB is defective",
            "E4-01" => "Fuser Warm-up Temperature Fuser Thermistor is dirty. Thermistor position is incorrect. Fuser temperature is low. (Adjust F6-31) Thermistor is defective. Fuser Lamp connector is disconnected. Fuser Thermostat is defective. Fuser Lamp is defective. HTC PCB connector is disconnected. HTC PCB is defective",
            "E4-02" => "Paper Jam Paper Jam in Fuser Unit. Paper Exit Sensor 1 or 2 is disconnected. Paper Exit Sensor 1 or 2 is defective. DRV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective",
            "E4-10" => "Exhaust Fan Motor(1) rotation Exhaust Fan connector is disconnected. Exhaust Fan is defective. LVPS connector is disconnected.LVPS is defective. LPC PCB is defective",
            "E4-11" => "Exhaust Fan Motor(2) rotation Exhaust Fan connector is disconnected. Exhaust Fan is defective. LVPS connector is disconnected. LVPS is defective. LPC PCB is defective",
            "E4-12" => "Exhaust Fan Motor(3) rotation Exhaust Fan connector is disconnected. Exhaust Fan is defective. LVPS connector is disconnected.LVPS is defective. LPC PCB is defective",
            "E5-01" => "Vp (+24V, printer) SPC PCB connector is disconnected. SPC PCB is defective",
            "E5-05" => "Vp (+24V, scanner) SPC PCB connector is disconnected. SPC PCB is defective",
            "E5-11" => "Printer Engine Communication abnormal SPC PCB connector is disconnected. SPC PCB is defective. SC PCB connector is disconnected. SC PCB is defective",
            "E5-12" => "Scanner Engine Communication abnormal",
            "E5-17" => "Scanner synchronization",
            "E5-19" => "Scanner Line synchronization",
            "E5-22" => "Finisher communication SPC PCB connector is disconnected. SPC PCB is defective. IPC PCB is disconnected. IPC PCB is defective. Finisher Interface Cable is disconnected. OP LVPS connector is disconnected. OP LVPS is defective. DC PCB connector is disconnected.Finisher is defective",
            "E5-40" => "Sort Memory Abnormal Sort Memory defective. SC PCB connector is disconnected. SC PCB defective",
            "E5-42" => "Total Counter connection Total Counter connector is disconnected. Total Counter is defective. DRV PCB connector is disconnected. DRV PCB is defective",
            "E5-60" => "Power Supply Cooling Fan Motor rotation Cooling Fan connector is disconnected. Cooling Fan is defective. RV PCB connector is disconnected. DRV PCB is defective. SPC PCB connector is disconnected. SPC PCB is defective. LVPS is defective",
            "E7-20" => "Finisher Paper Transport Motor",
            "E7-21" => "Finisher Paper Exit Motor",
            "E7-22" => "Finisher Damper Motor",
            "E7-23" => "Finisher Staple Motor",
            "E7-24" => "Finisher Staple Sift Motor",
            "E7-25" => "Finisher Paper Height Sensor",
            "E7-26" => "Finisher Backup RAM Data",
            "E7-27" => "Finisher Tray Shift Motor",
            "E7-28" => "Finisher Punch Motor",
            "E7-29" => "Finisher Punch Shift Motor",
            "E7-40" => "Finisher Saddle-Stitch Communication",
            "E7-41" => "Finisher Saddle Positioning Plate Motor",
            "E7-42" => "Finisher Saddle Folding Motor",
            "E7-43" => "Finisher Saddle Guide Motor",
            "E7-44" => "Finisher Saddle Alignment Motor",
            "E7-45" => "Finisher Saddle Rear Staple Motor",
            "E7-46" => "Finisher Saddle Front Staple Motor",
            "E7-47" => "Finisher Saddle Push Motor",
            "E7-48" => "Finisher Swing Motor",
            "E7-49" => "Finisher Sensor Connector",
            "E7-50" => "Finisher Micro Switch",
            "E7-51" => "Finisher Delivery Motor",
            "E7-52" => "Finisher Paddle Motor",
            "E7-53" => "Finisher Saddle Folding Sensor",
            "E7-54" => "Finisher Punch Communication",
            "E7-55" => "Finisher Punch Power Supply",
            "E7-56" => "Finisher Punch Registration Sensor",
            "E7-57" => "Finisher Punch Sensor (Horizontal Registration)",
            "E7-58" => "Finisher Punch Sensor (Waste Full)",
            "E7-90" => "Hardware Key Abnormal Incorrect Hardware Key is installed. Hardware Key is defective",
            "E7-91" => "Data Security Kit Abnormal Hardware Key for Data Security Kit is not installed"
        }
dp.each do |code, desc|
  Code.create(code: code, description: desc, model_id: 48)
  Code.create(code: code, description: desc, model_id: 49)
  Code.create(code: code, description: desc, model_id: 50)
  Code.create(code: code, description: desc, model_id: 51)
  Code.create(code: code, description: desc, model_id: 52)
  Code.create(code: code, description: desc, model_id: 53)
end

